### ISSUE TITLE
Cannot read property 'getContentResolver' of Undefined file 

### ISSUE THREAD

**Issue by uioporqwerty** [toddanglin/nativescript-trace-raven#3]
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

TypeError: Cannot read property 'getContentResolver' of undefined
File: "file:///data/data/org.nativescript.Audible/files/app/tns_modules/tns-core-modules/platform/platform.js, line: 79, column: 81

StackTrace: 
Frame: function:'get', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/tns-core-modules/platform/platform.js', line: 79, column: 82
Frame: function:'TraceRaven.initRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 42, column: 40
Frame: function:'TraceRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 22, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.Audible/files/app/app.js', line: 15, column: 17
Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'getContentResolver' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'get', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/tns-core-modules/platform/platform.js', line: 79, column: 82
Frame: function:'TraceRaven.initRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 42, column: 40
Frame: function:'TraceRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 22, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.Audible/files/app/app.js', line: 15, column: 17
Frame: function:'require', file:'', line: 1, column: 266


at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
at android.app.ActivityThread.-wrap3(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

TypeError: Cannot read property 'getContentResolver' of undefined
File: "file:///data/data/org.nativescript.Audible/files/app/tns_modules/tns-core-modules/platform/platform.js, line: 79, column: 81

StackTrace: 
Frame: function:'get', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/tns-core-modules/platform/platform.js', line: 79, column: 82
Frame: function:'TraceRaven.initRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 42, column: 40
Frame: function:'TraceRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 22, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.Audible/files/app/app.js', line: 15, column: 17
Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'getContentResolver' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'get', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/tns-core-modules/platform/platform.js', line: 79, column: 82
Frame: function:'TraceRaven.initRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 42, column: 40
Frame: function:'TraceRaven', file:'file:///data/data/org.nativescript.Audible/files/app/tns_modules/nativescript-trace-raven/trace-raven.js', line: 22, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.Audible/files/app/app.js', line: 15, column: 17
Frame: function:'require', file:'', line: 1, column: 266


at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:504)
at com.tns.Runtime.run(Runtime.java:499)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
... 8 more
```

Is this plugin still supported by the latest version of nativescript 3.0.1? The platform.ts file is no longer there.

**Comment by wassimdevox** [comment]
i have the same problem

**Comment by toddanglin** [comment]
Sorry for not following-up earlier. I just published an update to this plugin (v1.1.1) and verified that it works as expected on the latest versions of {N} on iOS (v3.4.1). I have not done much testing on Android. If you (or others) are still stuck on this issue (or want to give it another try), let me know if the problem persists.
